# -*- coding: utf-8 -*-
"""Agglomerative Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcd3TcDBL-Fq4TaUitxJ-PKfbFzFKrW5

**Hierarchical Clustering **
                         * Agglomerative CLustering *
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs

data = make_blobs(n_features=100 , n_samples=20,centers=4,cluster_std=  1.2,random_state=42)

data

points= data[0]

points

import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering

"""Bottom up approach"""

dendogram = sch.dendrogram(sch.linkage(points,method='ward'))
plt.title('ward')
plt.xlabel('Points')
plt.ylabel('Distance')
plt.show()

plt.scatter(data[0][:,0],data[0][:,1],)

# perform the actual cluster
hc = AgglomerativeClustering(n_clusters=2,linkage='ward')

y_hc = hc.fit_predict(points)

plt.scatter(points[y_hc==0,0],points[y_hc==0,1],s=100,c='red')
plt.scatter(points[y_hc==1,0],points[y_hc==1,1],s=100,c='blue')
plt.scatter(points[y_hc==2,0],points[y_hc==2,1],s=100,c='yellow')
plt.scatter(points[y_hc==3,0],points[y_hc==3,1],s=100,c='pink')
plt.scatter(points[y_hc==1,5],points[y_hc==1,2],s=100,c='orange')

dendogram = sch.dendrogram(sch.linkage(points,method='single'))
plt.title('Single')
plt.xlabel('Points')
plt.ylabel('Distance')
plt.show()

dendogram = sch.dendrogram(sch.linkage(points,method='complete'))
plt.title('Complete')
plt.xlabel('Points')
plt.ylabel('Distance')
plt.show()

dendogram = sch.dendrogram(sch.linkage(points,method='average'))
plt.title('Average')
plt.xlabel('Points')
plt.ylabel('Distance')
plt.show()

